# Generated by Django 6.0.2 on 2026-05-29 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_useractivity_userpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_avatar_change',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
