# Generated by Django 6.0.2 on 2026-08-13 17:51

import my_site.media_naming
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_last_token_generated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=my_site.media_naming.StaticMediaUploadTo('avatars')),
        ),
    ]
