# 常见漏洞扫描、WordPress 探测、WebSocket 探测、配置文件探测
location ~* ^/(wp-|wordpress|xmlrpc\.php|wp-login\.php|wp-json|wp-includes|wp-content) {
    return 444;
}

location ~* ^/(\.env|\.git|\.idea|\.vscode|\.ftpconfig|\.remote-sync\.json|\.svn|\.hg) {
    return 444;
}

location ~* ^/(socket\.io|ws|ws/|signalr|pusher|realtime|api/ws|api/websocket|api/socket|api/live|api/realtime|api/pusher|api/signalr) {
    return 444;
}

location ~* ^/(sslvpn_logon\.shtml|cgi-bin|cgi-mod|phpmyadmin|pma|adminer|\.well-known/security) {
    return 444;
}

location ~* ^/(\+CSCOE\+|\+CSCOT\+|AHT|CACHE|EndUserPortal\.jsp|Guest\.aspx|Login(?:\.jsp|/Login)?|Orion/Login\.aspx|RASHTML5Gateway|wsman|WebInterface/login\.html|_layouts/15/error\.aspx|appliance|authorization\.do) {
    return 444;
}