server {
    listen 80;
    server_name 38.76.217.137;  # 或者您的域名
    client_max_body_size 100M;

    location /static/ {
        alias /static/;
    }

    # 重要：让 Nginx 处理媒体文件
    location /media/ {
        alias /media/;  # 对应 docker-compose.yml 里的挂载路径
        # 所有以 /media/ 开头的请求（如 /media/audio/xxx.mp3），Nginx 将直接返回文件
    }

    location / {
        proxy_pass http://web:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}