# Generated by Django 6.0.2 on 2026-02-09 09:06

from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_post_tags"),
    ]

    operations = [TrigramExtension()]
