# Generated by Django 6.0.2 on 2026-06-21 18:46

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_audiopost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audiopost',
            options={'ordering': ['-created']},
        ),
        migrations.RenameField(
            model_name='audiopost',
            old_name='title',
            new_name='music_name',
        ),
        migrations.AddField(
            model_name='audiopost',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='audiopost',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='audiopost',
            index=models.Index(fields=['created'], name='blog_audiop_created_9bfbd6_idx'),
        ),
    ]
