# Generated by Django 6.0.2 on 2026-08-13 17:51

import my_site.media_naming
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_rename_blog_videop_created_6d737c_idx_blog_videop_created_5b5b0f_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiopost',
            name='audio_file',
            field=models.FileField(upload_to=my_site.media_naming.DatedMediaUploadTo('audio')),
        ),
        migrations.AlterField(
            model_name='audiopost',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=my_site.media_naming.DatedMediaUploadTo('audio/covers')),
        ),
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=my_site.media_naming.DatedMediaUploadTo('comments')),
        ),
        migrations.AlterField(
            model_name='post',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=my_site.media_naming.DatedMediaUploadTo('posts')),
        ),
        migrations.AlterField(
            model_name='videopost',
            name='video_file',
            field=models.FileField(upload_to=my_site.media_naming.DatedMediaUploadTo('videos')),
        ),
    ]
