# Generated by Django 6.0.2 on 2026-08-31 08:38

import my_site.media_naming
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_alter_audiopost_audio_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videopost',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=my_site.media_naming.DatedMediaUploadTo('videos')),
        ),
    ]
