# Generated by Django 6.0.2 on 2026-08-13 17:51

from django.db import migrations, models

import my_site.media_naming


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0005_alter_albumimage_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="imagepost",
            options={"verbose_name": "Gallery", "verbose_name_plural": "Gallery"},
        ),
        migrations.AlterField(
            model_name="albumimage",
            name="image",
            field=models.ImageField(
                upload_to=my_site.media_naming.DatedMediaUploadTo("albums")
            ),
        ),
        migrations.AlterField(
            model_name="imagepost",
            name="image",
            field=models.ImageField(
                upload_to=my_site.media_naming.DatedMediaUploadTo("gallery")
            ),
        ),
    ]
